#index:
#    path: /
#    controller: App\Controller\DefaultController::index

personas:
    type    : rest
    resource: App\Controller\Rest\PersonasController
    prefix  : rest

dates:
    type    : rest
    resource: App\Controller\Rest\DatesController
    prefix  : rest

users:
    type    : rest
    resource: App\Controller\Rest\UsersController
    prefix  : rest

tokens:
    type    : rest
    resource: App\Controller\Rest\TokensController
    prefix  : rest